name: Full build release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create (e.g. v1.2.3)"
        required: true
      message:
        description: "Tag message (annotated tag)"
        default: "Automated release"
        required: false

permissions:
  contents: write

jobs:
  create_tag:
    name: Create Git Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Create annotated tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "${{ github.event.inputs.tag }}" -m "${{ github.event.inputs.message }}"
          git push origin "${{ github.event.inputs.tag }}"

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: create_tag

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ez80asm-linux_x86_64.tar.gz
          - os: self-hosted
            artifact_name: ez80asm-linux_aarch64.tar.gz
          - os: macos-latest
            artifact_name: ez80asm-darwin_arm64.tar.gz
          - os: windows-2022
            artifact_name: ez80asm.exe

    steps:
      - uses: actions/checkout@v6

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y build-essential git make zip cmake texinfo ninja-build libgmp-dev libmpfr-dev bison flex python3-pip python3-ply zlib1g-dev binutils
          curl -L -o "agondev-linux_x86_64.tar.gz" "https://github.com/AgonPlatform/agondev/releases/latest/download/agondev-linux_x86_64.tar.gz"
          tar xf agondev-linux_x86_64.tar.gz

      # macOS dependencies
      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install texinfo zlib

      # Windows dependencies
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2022'
        uses: microsoft/setup-msbuild@v2

      - name: Make agon binary
        if: matrix.os == 'ubuntu-latest'
        run: |
          export PATH=./agondev/bin:$PATH
          make clean
          make agon
          cp ./release/ez80asm.bin .

      - name: Make platform binary
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'self-hosted' || matrix.os == 'macos-latest'
        run: |
          make clean
          make
          cp ./release/*.tar.gz .

      - name: Run all tests
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'self-hosted' || matrix.os == 'macos-latest'
        run: ./test.sh

      - name: Make windows binary
        if: matrix.os == 'windows-2022'
        run: |
          msbuild src\vsproject\ez80asm.sln -t:rebuild -verbosity:diag -property:Configuration=Release
          cp src\vsproject\x64\Release\ez80asm.exe .

      - name: Upload agon artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ez80asm.bin
          path: ez80asm.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    name: Create draft release and upload assets
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v6

      - name: Download all built artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
          merge-multiple: true

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.event.inputs.tag }}
          draft: true
